#!/usr/bin/env bash

# start in boxnav directory
# have Git Bash installed
# open new terminal ('Git Bash' from '+' dropdown menu)
# make script executabe if you haven't already ('chmod +x inference_run.sh' in terminal)
# run script ('./inference_run.sh' in terminal)

# Inference on ResNet18
python inference.py InferencePerfectStaticResNet18 Summer2024Official "Run 5 inference trials on Perfect Static model trained on ResNet18" PerfectStaticModel-ResNet18-Perfect100kData-rep00 InferencePerfectStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video PerfectStaticResNet18Video
python inference.py InferencePerfectRand10ResNet18 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on ResNet18" PerfectRand10Model-ResNet18-Perfect100kRandEvery10Data-rep00 InferencePerfectStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video PerfectRand10ResNet18Video
python inference.py InferencePerfectRand50ResNet18 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on ResNet18" PerfectRand50Model-ResNet18-Perfect100kRandEvery50Data-rep00 InferencePerfectStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video PerfectRand50ResNet18Video

python inference.py InferenceWanderingStaticResNet18 Summer2024Official "Run 5 inference trials on Wandering Static model trained on ResNet18" WanderingStaticResNet18-ResNet18-Wandering100kData-rep00 InferenceWanderingStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video WanderingStaticResNet18Video
python inference.py InferenceWanderingRand10ResNet18 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on ResNet18" WanderingRand10ResNet18-ResNet18-Wandering100kRandEvery10Data-rep00 InferenceWanderingStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video WanderingRand10ResNet18Video
python inference.py InferenceWanderingRand50ResNet18 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on ResNet18" WanderingRand50ResNet18-ResNet18-Wandering100kRandEvery50Data-rep00 InferenceWanderingStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video WanderingRand50ResNet18Video

python inference.py InferenceTeleportingStaticResNet18 Summer2024Official "Run 5 inference trials on Teleporting Static model trained on ResNet18" TeleportingStaticResNet18-ResNet18-Teleporting100kData-rep00 InferenceTeleportingStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video TeleportingStaticResNet18Video
python inference.py InferenceTeleportingRand10ResNet18 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on ResNet18" TeleportingRand10ResNet18-ResNet18-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video TeleportingRand10ResNet18Video
python inference.py InferenceTeleportingRand50ResNet18 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on ResNet18" TeleportingRand50ResNet18-ResNet18-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingStaticResNet18 --max_actions 500 --num_trials 5 --save_map_video TeleportingRand50ResNet18Video

# Inference on MobileNetV4
python inference.py InferencePerfectStaticMobileNetV4 Summer2024Official "Run 5 inference trials on Perfect Static model trained on MobileNetV4" PerfectStaticMobileNetV4-MobileNetV4-Perfect100kData-rep00 InferencePerfectStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video PerfectStaticMobileNetV4Video
python inference.py InferencePerfectRand10MobileNetV4 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on MobileNetV4" PerfectRand10MobileNetV4-MobileNetV4-Perfect100kRandEvery10Data-rep00 InferencePerfectStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video PerfectRand10MobileNetV4Video
python inference.py InferencePerfectRand50MobileNetV4 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on MobileNetV4" PerfectRand50MobileNetV4-MobileNetV4-Perfect100kRandEvery50Data-rep00 InferencePerfectStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video PerfectRand50MobileNetV4Video

python inference.py InferenceWanderingStaticMobileNetV4 Summer2024Official "Run 5 inference trials on Wandering Static model trained on MobileNetV4" WanderingStaticMobileNetV4-MobileNetV4-Wandering100kData-rep00 InferenceWanderingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video WanderingStaticMobileNetV4Video
python inference.py InferenceWanderingRand10MobileNetV4 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on MobileNetV4" WanderingRand10MobileNetV4-MobileNetV4-Wandering100kRandEvery10Data-rep00 InferenceWanderingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video WanderingRand10MobileNetV4Video
python inference.py InferenceWanderingRand50MobileNetV4 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on MobileNetV4" WanderingRand50MobileNetV4-MobileNetV4-Wandering100kRandEvery50Data-rep00 InferenceWanderingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video WanderingRand50MobileNetV4Video

python inference.py InferenceTeleportingStaticMobileNetV4 Summer2024Official "Run 5 inference trials on Teleporting Static model trained on MobileNetV4" TeleportingStaticMobileNetV4-MobileNetV4-Teleporting100kData-rep00 InferenceTeleportingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video TeleportingStaticMobileNetV4Video
python inference.py InferenceTeleportingRand10MobileNetV4 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on MobileNetV4" TeleportingRand10MobileNetV4-MobileNetV4-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video TeleportingRand10MobileNetV4Video
python inference.py InferenceTeleportingRand50MobileNetV4 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on MobileNetV4" TeleportingRand50MobileNetV4-MobileNetV4-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_map_video TeleportingRand50MobileNetV4Video

# Inference on EfficientNet
python inference.py InferencePerfectStaticEfficientNet Summer2024Official "Run 5 inference trials on Perfect Static model trained on EfficientNet" PerfectStaticEfficientNet-EfficientNet-Perfect100kData-rep00 InferencePerfectStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video PerfectStaticEfficientNetVideo
python inference.py InferencePerfectRand10EfficientNet Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on EfficientNet" PerfectRand10EfficientNet-EfficientNet-Perfect100kRandEvery10Data-rep00 InferencePerfectStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video PerfectRand10EfficientNetVideo
python inference.py InferencePerfectRand50EfficientNet Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on EfficientNet" PerfectRand50EfficientNet-EfficientNet-Perfect100kRandEvery50Data-rep00 InferencePerfectStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video PerfectRand50EfficientNetVideo

python inference.py InferenceWanderingStaticEfficientNet Summer2024Official "Run 5 inference trials on Wandering Static model trained on EfficientNet" WanderingStaticEfficientNet-EfficientNet-Wandering100kData-rep00 InferenceWanderingStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video WanderingStaticEfficientNetVideo
python inference.py InferenceWanderingRand10EfficientNet Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on EfficientNet" WanderingRand10EfficientNet-EfficientNet-Wandering100kRandEvery10Data-rep00 InferenceWanderingStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video WanderingRand10EfficientNetVideo
python inference.py InferenceWanderingRand50EfficientNet Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on EfficientNet" WanderingRand50EfficientNet-EfficientNet-Wandering100kRandEvery50Data-rep00 InferenceWanderingStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video WanderingRand50EfficientNetVideo

python inference.py InferenceTeleportingStaticEfficientNet Summer2024Official "Run 5 inference trials on Teleporting Static model trained on EfficientNet" TeleportingStaticEfficientNet-EfficientNet-Teleporting100kData-rep00 InferenceTeleportingStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video TeleportingStaticEfficientNetVideo
python inference.py InferenceTeleportingRand10EfficientNet Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on EfficientNet" TeleportingRand10EfficientNet-EfficientNet-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video TeleportingRand10EfficientNetVideo
python inference.py InferenceTeleportingRand50EfficientNet Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on EfficientNet" TeleportingRand50EfficientNet-EfficientNet-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingStaticEfficientNet --max_actions 500 --num_trials 5 --save_map_video TeleportingRand50EfficientNetVideo

# # Inference on ConvNextV2Atto
# python inference.py InferencePerfectStaticConvNextV2Atto Summer2024Official "Run 5 inference trials on Perfect Static model trained on ConvNextV2Atto" PerfectStaticConvNextV2Atto-ConvNextV2Atto-Perfect100kData-rep00 InferencePerfectStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video PerfectStaticConvNextV2AttoVideo
# python inference.py InferencePerfectRand10ConvNextV2Atto Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on ConvNextV2Atto" PerfectRand10ConvNextV2Atto-ConvNextV2Atto-Perfect100kRandEvery10Data-rep00 InferencePerfectStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video PerfectRand10ConvNextV2AttoVideo
# python inference.py InferencePerfectRand50ConvNextV2Atto Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on ConvNextV2Atto" PerfectRand50ConvNextV2Atto-ConvNextV2Atto-Perfect100kRandEvery50Data-rep00 InferencePerfectStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video PerfectRand50ConvNextV2AttoVideo

# python inference.py InferenceWanderingStaticConvNextV2Atto Summer2024Official "Run 5 inference trials on Wandering Static model trained on ConvNextV2Atto" WanderingStaticConvNextV2Atto-ConvNextV2Atto-Wandering100kData-rep00 InferenceWanderingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video WanderingStaticConvNextV2AttoVideo
# python inference.py InferenceWanderingRand10ConvNextV2Atto Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on ConvNextV2Atto" WanderingRand10ConvNextV2Atto-ConvNextV2Atto-Wandering100kRandEvery10Data-rep00 InferenceWanderingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video WanderingRand10ConvNextV2AttoVideo
# python inference.py InferenceWanderingRand50ConvNextV2Atto Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on ConvNextV2Atto" WanderingRand50ConvNextV2Atto-ConvNextV2Atto-Wandering100kRandEvery50Data-rep00 InferenceWanderingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video WanderingRand50ConvNextV2AttoVideo

# python inference.py InferenceTeleportingStaticConvNextV2Atto Summer2024Official "Run 5 inference trials on Teleporting Static model trained on ConvNextV2Atto" TeleportingStaticConvNextV2Atto-ConvNextV2Atto-Teleporting100kData-rep00 InferenceTeleportingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video TeleportingStaticConvNextV2AttoVideo
# python inference.py InferenceTeleportingRand10ConvNextV2Atto Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on ConvNextV2Atto" TeleportingRand10ConvNextV2Atto-ConvNextV2Atto-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video TeleportingRand10ConvNextV2AttoVideo
# python inference.py InferenceTeleportingRand50ConvNextV2Atto Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on ConvNextV2Atto" TeleportingRand50ConvNextV2Atto-ConvNextV2Atto-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_map_video TeleportingRand50ConvNextV2AttoVideo

# # Inference on ConvNextV2Base
# python inference.py InferencePerfectStaticConvNextV2Base Summer2024Official "Run 5 inference trials on Perfect Static model trained on ConvNextV2Base" PerfectStaticConvNextV2Base-ConvNextV2Base-Perfect100kData-rep00 InferencePerfectStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video PerfectStaticConvNextV2BaseVideo
# python inference.py InferencePerfectRand10ConvNextV2Base Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on ConvNextV2Base" PerfectRand10ConvNextV2Base-ConvNextV2Base-Perfect100kRandEvery10Data-rep00 InferencePerfectStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video PerfectRand10ConvNextV2BaseVideo
# python inference.py InferencePerfectRand50ConvNextV2Base Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on ConvNextV2Base" PerfectRand50ConvNextV2Base-ConvNextV2Base-Perfect100kRandEvery50Data-rep00 InferencePerfectStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video PerfectRand50ConvNextV2BaseVideo

# python inference.py InferenceWanderingStaticConvNextV2Base Summer2024Official "Run 5 inference trials on Wandering Static model trained on ConvNextV2Base" WanderingStaticConvNextV2Base-ConvNextV2Base-Wandering100kData-rep00 InferenceWanderingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video WanderingStaticConvNextV2BaseVideo
# python inference.py InferenceWanderingRand10ConvNextV2Base Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on ConvNextV2Base" WanderingRand10ConvNextV2Base-ConvNextV2Base-Wandering100kRandEvery10Data-rep00 InferenceWanderingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video WanderingRand10ConvNextV2BaseVideo
# python inference.py InferenceWanderingRand50ConvNextV2Base Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on ConvNextV2Base" WanderingRand50ConvNextV2Base-ConvNextV2Base-Wandering100kRandEvery50Data-rep00 InferenceWanderingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video WanderingRand50ConvNextV2BaseVideo

# python inference.py InferenceTeleportingStaticConvNextV2Base Summer2024Official "Run 5 inference trials on Teleporting Static model trained on ConvNextV2Base" TeleportingStaticConvNextV2Base-ConvNextV2Base-Teleporting100kData-rep00 InferenceTeleportingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video TeleportingStaticConvNextV2BaseVideo
# python inference.py InferenceTeleportingRand10ConvNextV2Base Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on ConvNextV2Base" TeleportingRand10ConvNextV2Base-ConvNextV2Base-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video TeleportingRand10ConvNextV2BaseVideo
# python inference.py InferenceTeleportingRand50ConvNextV2Base Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on ConvNextV2Base" TeleportingRand50ConvNextV2Base-ConvNextV2Base-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_map_video TeleportingRand50ConvNextV2BaseVideo
