#!/usr/bin/env bash

# start in boxnav directory
# have Git Bash installed
# open new terminal ('Git Bash' from '+' dropdown menu)
# make script executabe if you haven't already ('chmod +x inference_run.sh' in terminal)
# run script ('./inference_run.sh' in terminal)

# # Inference on ResNet18
# python inference.py InferencePerfectStaticResNet18 Summer2024Official "Run 5 inference trials on Perfect Static model trained on ResNet18" PerfectStaticModel-ResNet18-Perfect100kData-rep00 InferencePerfectStaticResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand10ResNet18 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on ResNet18" PerfectRand10Model-ResNet18-Perfect100kRandEvery10Data-rep00 InferencePerfectRand10ResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand50ResNet18 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on ResNet18" PerfectRand50Model-ResNet18-Perfect100kRandEvery50Data-rep00 InferencePerfectRand50ResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceWanderingStaticResNet18 Summer2024Official "Run 5 inference trials on Wandering Static model trained on ResNet18" WanderingStaticResNet18-ResNet18-Wandering100kData-rep00 InferenceWanderingStaticResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand10ResNet18 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on ResNet18" WanderingRand10ResNet18-ResNet18-Wandering100kRandEvery10Data-rep00 InferenceWanderingRand10ResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand50ResNet18 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on ResNet18" WanderingRand50ResNet18-ResNet18-Wandering100kRandEvery50Data-rep00 InferenceWanderingRand50ResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceTeleportingStaticResNet18 Summer2024Official "Run 5 inference trials on Teleporting Static model trained on ResNet18" TeleportingStaticResNet18-ResNet18-Teleporting100kData-rep00 InferenceTeleportingStaticResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand10ResNet18 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on ResNet18" TeleportingRand10ResNet18-ResNet18-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingRand10ResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand50ResNet18 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on ResNet18" TeleportingRand50ResNet18-ResNet18-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingRand50ResNet18 --max_actions 500 --num_trials 5 --save_minimap_video 

# Inference on MobileNetV4
python inference.py InferencePerfectStaticMobileNetV4 Summer2024Official "Run 5 inference trials on Perfect Static model trained on MobileNetV4" PerfectStaticModel-MobileNetV4-Perfect100kData-rep00 InferencePerfectStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 
python inference.py InferencePerfectRand10MobileNetV4 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on MobileNetV4" PerfectRand10Model-MobileNetV4-Perfect100kRandEvery10Data-rep00 InferencePerfectRand10MobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 
python inference.py InferencePerfectRand50MobileNetV4 Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on MobileNetV4" PerfectRand50Model-MobileNetV4-Perfect100kRandEvery50Data-rep00 InferencePerfectRand50MobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceWanderingStaticMobileNetV4 Summer2024Official "Run 5 inference trials on Wandering Static model trained on MobileNetV4" WanderingStaticMobileNetV4-MobileNetV4-Wandering100kData-rep00 InferenceWanderingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand10MobileNetV4 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on MobileNetV4" WanderingRand10MobileNetV4-MobileNetV4-Wandering100kRandEvery10Data-rep00 InferenceWanderingRand10MobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video
# python inference.py InferenceWanderingRand50MobileNetV4 Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on MobileNetV4" WanderingRand50MobileNetV4-MobileNetV4-Wandering100kRandEvery50Data-rep00 InferenceWanderingRand50MobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 

python inference.py InferenceTeleportingStaticMobileNetV4 Summer2024Official "Run 5 inference trials on Teleporting Static model trained on MobileNetV4" TeleportingStaticModel-MobileNetV4-Teleporting100kData-rep00 InferenceTeleportingStaticMobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 
python inference.py InferenceTeleportingRand10MobileNetV4 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on MobileNetV4" TeleportingRand10Model-MobileNetV4-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingRand10MobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 
python inference.py InferenceTeleportingRand50MobileNetV4 Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on MobileNetV4" TeleportingRand50Model-MobileNetV4-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingRand50MobileNetV4 --max_actions 500 --num_trials 5 --save_minimap_video 

# # Inference on EfficientNet
# python inference.py InferencePerfectStaticEfficientNet Summer2024Official "Run 5 inference trials on Perfect Static model trained on EfficientNet" PerfectStaticEfficientNet-EfficientNet-Perfect100kData-rep00 InferencePerfectStaticEfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand10EfficientNet Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on EfficientNet" PerfectRand10EfficientNet-EfficientNet-Perfect100kRandEvery10Data-rep00 InferencePerfectRand10EfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand50EfficientNet Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on EfficientNet" PerfectRand50EfficientNet-EfficientNet-Perfect100kRandEvery50Data-rep00 InferencePerfectRand50EfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceWanderingStaticEfficientNet Summer2024Official "Run 5 inference trials on Wandering Static model trained on EfficientNet" WanderingStaticEfficientNet-EfficientNet-Wandering100kData-rep00 InferenceWanderingStaticEfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand10EfficientNet Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on EfficientNet" WanderingRand10EfficientNet-EfficientNet-Wandering100kRandEvery10Data-rep00 InferenceWanderingRand10EfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand50EfficientNet Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on EfficientNet" WanderingRand50EfficientNet-EfficientNet-Wandering100kRandEvery50Data-rep00 InferenceWanderingRand50EfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceTeleportingStaticEfficientNet Summer2024Official "Run 5 inference trials on Teleporting Static model trained on EfficientNet" TeleportingStaticEfficientNet-EfficientNet-Teleporting100kData-rep00 InferenceTeleportingStaticEfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand10EfficientNet Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on EfficientNet" TeleportingRand10EfficientNet-EfficientNet-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingRand10EfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand50EfficientNet Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on EfficientNet" TeleportingRand50EfficientNet-EfficientNet-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingRand50EfficientNet --max_actions 500 --num_trials 5 --save_minimap_video 

# # Inference on ConvNextV2Atto
# python inference.py InferencePerfectStaticConvNextV2Atto Summer2024Official "Run 5 inference trials on Perfect Static model trained on ConvNextV2Atto" PerfectStaticConvNextV2Atto-ConvNextV2Atto-Perfect100kData-rep00 InferencePerfectStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand10ConvNextV2Atto Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on ConvNextV2Atto" PerfectRand10ConvNextV2Atto-ConvNextV2Atto-Perfect100kRandEvery10Data-rep00 InferencePerfectRand10ConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand50ConvNextV2Atto Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on ConvNextV2Atto" PerfectRand50ConvNextV2Atto-ConvNextV2Atto-Perfect100kRandEvery50Data-rep00 InferencePerfectRand50ConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceWanderingStaticConvNextV2Atto Summer2024Official "Run 5 inference trials on Wandering Static model trained on ConvNextV2Atto" WanderingStaticConvNextV2Atto-ConvNextV2Atto-Wandering100kData-rep00 InferenceWanderingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand10ConvNextV2Atto Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on ConvNextV2Atto" WanderingRand10ConvNextV2Atto-ConvNextV2Atto-Wandering100kRandEvery10Data-rep00 InferenceWanderingRand10ConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand50ConvNextV2Atto Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on ConvNextV2Atto" WanderingRand50ConvNextV2Atto-ConvNextV2Atto-Wandering100kRandEvery50Data-rep00 InferenceWanderingRand50ConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceTeleportingStaticConvNextV2Atto Summer2024Official "Run 5 inference trials on Teleporting Static model trained on ConvNextV2Atto" TeleportingStaticConvNextV2Atto-ConvNextV2Atto-Teleporting100kData-rep00 InferenceTeleportingStaticConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand10ConvNextV2Atto Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on ConvNextV2Atto" TeleportingRand10ConvNextV2Atto-ConvNextV2Atto-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingRand10ConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand50ConvNextV2Atto Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on ConvNextV2Atto" TeleportingRand50ConvNextV2Atto-ConvNextV2Atto-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingRand50ConvNextV2Atto --max_actions 500 --num_trials 5 --save_minimap_video 

# # Inference on ConvNextV2Base
# python inference.py InferencePerfectStaticConvNextV2Base Summer2024Official "Run 5 inference trials on Perfect Static model trained on ConvNextV2Base" PerfectStaticConvNextV2Base-ConvNextV2Base-Perfect100kData-rep00 InferencePerfectStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand10ConvNextV2Base Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on ConvNextV2Base" PerfectRand10ConvNextV2Base-ConvNextV2Base-Perfect100kRandEvery10Data-rep00 InferencePerfectRand10ConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand50ConvNextV2Base Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on ConvNextV2Base" PerfectRand50ConvNextV2Base-ConvNextV2Base-Perfect100kRandEvery50Data-rep00 InferencePerfectRand50ConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceWanderingStaticConvNextV2Base Summer2024Official "Run 5 inference trials on Wandering Static model trained on ConvNextV2Base" WanderingStaticConvNextV2Base-ConvNextV2Base-Wandering100kData-rep00 InferenceWanderingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand10ConvNextV2Base Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on ConvNextV2Base" WanderingRand10ConvNextV2Base-ConvNextV2Base-Wandering100kRandEvery10Data-rep00 InferenceWanderingRand10ConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand50ConvNextV2Base Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on ConvNextV2Base" WanderingRand50ConvNextV2Base-ConvNextV2Base-Wandering100kRandEvery50Data-rep00 InferenceWanderingRand50ConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceTeleportingStaticConvNextV2Base Summer2024Official "Run 5 inference trials on Teleporting Static model trained on ConvNextV2Base" TeleportingStaticConvNextV2Base-ConvNextV2Base-Teleporting100kData-rep00 InferenceTeleportingStaticConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand10ConvNextV2Base Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on ConvNextV2Base" TeleportingRand10ConvNextV2Base-ConvNextV2Base-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingRand10ConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand50ConvNextV2Base Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on ConvNextV2Base" TeleportingRand50ConvNextV2Base-ConvNextV2Base-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingRand50ConvNextV2Base --max_actions 500 --num_trials 5 --save_minimap_video 


# # Inference on ViT
# python inference.py InferencePerfectStaticViT Summer2024Official "Run 5 inference trials on Perfect Static model trained on ViT" PerfectStaticViT-ViT-Perfect100kData-rep00 InferencePerfectStaticViT --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand10ViT Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 10 model trained on ViT" PerfectRand10ViT-ViT-Perfect100kRandEvery10Data-rep00 InferencePerfectRand10ViT --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferencePerfectRand50ViT Summer2024Official "Run 5 inference trials on Perfect Randomized Textures every 50 model trained on ViT" PerfectRand50ViT-ViT-Perfect100kRandEvery50Data-rep00 InferencePerfectRand50ViT --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceWanderingStaticViT Summer2024Official "Run 5 inference trials on Wandering Static model trained on ViT" WanderingStaticViT-ViT-Wandering100kData-rep00 InferenceWanderingStaticViT --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand10ViT Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 10 model trained on ViT" WanderingRand10ViT-ViT-Wandering100kRandEvery10Data-rep00 InferenceWanderingRand10ViT --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceWanderingRand50ViT Summer2024Official "Run 5 inference trials on Wandering Randomized Textures every 50 model trained on ViT" WanderingRand50ViT-ViT-Wandering100kRandEvery50Data-rep00 InferenceWanderingRand50ViT --max_actions 500 --num_trials 5 --save_minimap_video 

# python inference.py InferenceTeleportingStaticViT Summer2024Official "Run 5 inference trials on Teleporting Static model trained on ViT" TeleportingStaticViT-ViT-Teleporting100kData-rep00 InferenceTeleportingStaticViT --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand10ViT Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 10 model trained on ViT" TeleportingRand10ViT-ViT-Teleporting100kRandEvery10Data-rep00 InferenceTeleportingRand10ViT --max_actions 500 --num_trials 5 --save_minimap_video 
# python inference.py InferenceTeleportingRand50ViT Summer2024Official "Run 5 inference trials on Teleporting Randomized Textures every 50 model trained on ViT" TeleportingRand50ViT-ViT-Teleporting100kRandEvery50Data-rep00 InferenceTeleportingRand50ViT --max_actions 500 --num_trials 5 --save_minimap_video 
